### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by Infinyum** [Infinyum/ticketing_software#7]

**Comment by ghost** [comment]
je reprend le diagramme de cas d'utilisation qu'avait commencé jordane et je le complète

**Comment by ghost** [comment]
Jordane a quasiment tout fait, j'ai ajouté la gestion des listes sur les catégories d'intervention (genre perte de mot de passe, etc..) ainsi que la gestion des listes des compétences possibles pour les techniciens. Tout ca est géré par le responsable technique.
Je pense qu'on a pensé a tout en restant assez général. Need Review.
